### ISSUE TITLE
Write instructions for the Do-a-thon 

### ISSUE THREAD

**Issue by morchickit** [OpenHeroines/gender-doathon#1]
Those instructions should include:
1. What is a doathon?
2. Who can participate?
3. How can you participate?
4. Where it will take place?

**Comment by Hazwany** [comment]
Also, include few ground rules. Following are few examples that we can adopt:
- [https://www.ebgconsulting.com/Goodies/Assets/WrkshpGroundRules.pdf](https://www.ebgconsulting.com/Goodies/Assets/WrkshpGroundRules.pdf)
- [https://www.ndi.org/sites/default/files/Sample-Workshop-Groundrules.pdf](https://www.ndi.org/sites/default/files/Sample-Workshop-Groundrules.pdf)
- [https://hbr.org/2016/06/8-ground-rules-for-great-meetings](https://hbr.org/2016/06/8-ground-rules-for-great-meetings)

**Comment by Hazwany** [comment]
I have started a document here: [https://docs.google.com/document/d/1yxFbxck33j-k_1HP9mnYh6BbSo9aEr_te6766o9racQ/edit?usp=sharing](https://docs.google.com/document/d/1yxFbxck33j-k_1HP9mnYh6BbSo9aEr_te6766o9racQ/edit?usp=sharing)

**Comment by morchickit** [comment]
Instructions and code of conduct are not the same thing. Can we start a new issue for code of conduct? I was just think of taking the IODC one (which I wrote....)

**Comment by morchickit** [comment]
No I see that issue #10 is code of conduct. Nany, can we clean this and use the instructions in the readme file?
