### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by morchickit** [OpenHeroines/gender-doathon#10]
Add an event code of conduct

**Comment by Hazwany** [comment]
There are few examples of the code of conduct that we can adopt:
- [Internet Freedom Festival](https://www.internetfreedomfestival.org/wiki/index.php/Code_of_Conduct)
- [Women Who Code](https://www.womenwhocode.com/blog/code-of-conduct)

We should also consider adding a Complaint Registration Form. An example: [https://sites.google.com/dataviz.my/learndataeducation/guidelines/complaint-form](https://sites.google.com/dataviz.my/learndataeducation/guidelines/complaint-form) or [https://forms.icann.org/en/resources/compliance/registries/code-of-conduct/form](https://forms.icann.org/en/resources/compliance/registries/code-of-conduct/form).

**Comment by Hazwany** [comment]
I have started a document here: [https://docs.google.com/document/d/1yxFbxck33j-k_1HP9mnYh6BbSo9aEr_te6766o9racQ/edit?usp=sharing](https://docs.google.com/document/d/1yxFbxck33j-k_1HP9mnYh6BbSo9aEr_te6766o9racQ/edit?usp=sharing)

**Comment by morchickit** [comment]
I think we can just link to to the IODC code of conduct...
