### ISSUE TITLE
Write a blog post on how to participate in the doathon

### ISSUE THREAD

**Issue by morchickit** [OpenHeroines/gender-doathon#5]
So people who are not in the slack can join.

**Comment by Hazwany** [comment]
I can help to contribute in co-writing the blog post. Following are few points that we can start to look into and elaborate further:
- What is "Doathon"?
- Why is it important?
- Who is the target audience?
- What are the benefits of participating?
- Duration, time frame, venue
- How to sign up

**Comment by Hazwany** [comment]
I have started a document here: [https://docs.google.com/document/d/16lfunfn9wu2NX_eCyI1n3HLF_yRgGBkOgDbPXRV9dYs/edit?usp=sharing](https://docs.google.com/document/d/16lfunfn9wu2NX_eCyI1n3HLF_yRgGBkOgDbPXRV9dYs/edit?usp=sharing)
