### ISSUE TITLE
Create a Google Form where people can pitch project for the Do-A-thon 

### ISSUE THREAD

**Issue by morchickit** [OpenHeroines/gender-doathon#7]
We need a way for people to pitch their projects. 
This is how SPARC did it: 
https://sparcopen.github.io/doathon-dev/project.html
https://docs.google.com/forms/d/e/1FAIpQLSd_ptZY4xgc4vZAiMmsrjspPF3gUxOfOj_iBQ5ign3f5n5bqw/viewform

**Comment by Hazwany** [comment]
@morchickit, I have made some edits to the form: https://goo.gl/forms/TaUcsdOcgMfkrUA02

**Comment by morchickit** [comment]
This is now done.
