### ISSUE TITLE
Translate content to Spanish 

### ISSUE THREAD

**Issue by morchickit** [OpenHeroines/gender-doathon#8]
So it will be inclusive and including for the LATAM community.

**Comment by seleneyang** [comment]
Pao and I are translating this blog post to Spanish:

>https://openheroines.org/international-open-data-conference-2018-the-open-heroines-do-a-thon-39e255474435

Here's the translation document: 

> https://docs.google.com/document/d/1aUoIVfIAB0QKzTy8zOC50_DMuZRK1L7NAjA6BdcGYBc/edit
